"""Build deterministic, human-readable VulnAgent PR comments."""


def build_pr_comment(title: str, body_markdown: str, priority: str, pr_number: int | None = None) -> str:
    """Format the generated ticket content as an accurate PR conversation comment."""
    heading = "## VulnAgent Security Finding"
    pr_text = f" for PR **#{pr_number}**" if pr_number else ""
    return "\n".join([
        heading,
        "",
        f"**Finding:** {title}",
        f"**Priority:** {priority}",
        "",
        body_markdown.strip(),
        "",
        f"_Generated by VulnAgent{pr_text}. LLM output is a recommendation and should be validated according to repository security policy._",
    ])
