"""Build deterministic, human-readable VulnAgent PR review comments."""


def build_pr_comment(findings: list[dict], pr_number: int | None = None) -> str:
    lines = [
        "## VulnAgent Security Review",
        "",
        f"Analyzed findings: **{len(findings)}**" + (f" for PR **#{pr_number}**." if pr_number else "."),
        "",
    ]
    if not findings:
        lines.append("✅ No normalized security findings were produced.")
        return "\n".join(lines)

    for item in findings:
        title = item.get("finding_title", "Untitled finding")
        source = item.get("finding_source", "unknown")
        escalated = item.get("escalated", False)
        classification = next(
            (call.get("result", {}) for call in item.get("tool_calls", []) if call.get("tool") == "classify_severity"),
            {},
        )
        severity = classification.get("severity", "UNKNOWN")
        cvss = classification.get("cvss_score", "N/A")
        status = "🚨 Human review required" if escalated else "✅ Auto-triaged"
        lines.extend([
            f"### {severity}: {title}",
            f"- **Source:** {source}",
            f"- **CVSS estimate:** {cvss}",
            f"- **Status:** {status}",
            "",
        ])
    lines.append("_Generated by VulnAgent. LLM classifications are recommendations and should be validated according to repository security policy._")
    return "\n".join(lines)
